on: [push]

name: AzureSpringCloud

env:
  CLUSTER_NAME: yuchensp
  CLUSTER_RG: ycuhensp
  CONFIGSERVER_URL: https://github.com/yucwan/piggymetrics

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # checkout the repo
    - uses: actions/checkout@master
    
    # Maven Build and package
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # build and clean
    - name: maven build, clean
      run: |
        mvn clean package -D skipTests
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.75
        inlineScript: |
          az extension add --name spring-cloud
          az configure --defaults group=CLUSTER_RG
          az configure --defaults spring-cloud=CLUSTER_NAME
          az spring-cloud config-server git set --uri CONFIGSERVER_URL --label config
          az spring-cloud app create --name gateway --is-public true
          az spring-cloud app create --name auth-service
          az spring-cloud app create --name account-service
          az spring-cloud app deploy -n gateway --jar-path ${{ github.workspace }}/gateway/target/gateway.jar
          az spring-cloud app deploy -n account-service --jar-path ${{ github.workspace }}/account-service/target/account-service.jar
          az spring-cloud app deploy -n auth-service --jar-path ${{ github.workspace }}/auth-service/target/auth-service.jar
